### ISSUE TITLE
Cursor Issues with Text Selection

### ISSUE THREAD

**Issue by trigger-segfault** [icsharpcode/AvalonEdit#104]
After selecting text the cursor behaves incorrectly in the following situations.

* After dragging a selection the cursor no longer shows as an arrow over the selection.
* After selecting text on the last line of the document, the cursor shows as an arrow when below the selection.

**Comment by jimfoye** [comment]
I reproduced your bug in 5.0.3, but as far as I can tell, my PR #96 fixed this, because with that change I don't see the problem anymore.

I don't think your second bullet is actually a bug, if I'm understanding correctly. If your file ends with an extra linefeed, the cursor will go down to it, but nothing is actually selected there, so it shouldn't change.

**Comment by trigger-death** [comment]
I'll explain my second bullet in more detail:

Normally when your mouse cursor is below the last line of the editor, it should show as a text cursor. But when below selected text on the last line, it shows as the arrow cursor.

**Comment by jimfoye** [comment]
Does the arrow point to right? Or to the left? Also, do you have line numbers turned enabled?

**Comment by trigger-death** [comment]
To the left like the standard arrow. It also happens with or without line numbers. After further investigation it looks like this is the case because the editor still allows you to reach the text for drag and drop. So even if it's not standard on all editors, it seems this feature is functioning as it should.
