### ISSUE TITLE
Behavior of 'end' key is incorrect if 'show spaces' is not enabled

### ISSUE THREAD

**Issue by dgrunwald** [icsharpcode/AvalonEdit#12]
With show spaces on, the 'end' key jumps to the end of the line, after any whitespace.
With show spaces off, it jumps to the end of the line, but before any trailing whitespace.

The behavior should be consistent between the two settings. Also, I think the first behavior is more useful -- trailing whitespace usually is unintentional, and one should be able to find it by pressing 'end'. Notepad++ also jumps to the end of line after trailing whitespace.

**Comment by Herohtar** [comment]
It might be worth noting that the cause of the inconsistency was **textLine.TrailingWhitespaceLength**... the value of this property always seems to be **1** when 'show spaces' is on, no matter how many spaces there actually are.

**Comment by mike-ward** [comment]
I would like to lobby to have this fixed, or at least overridable. User has reported the issue in https://github.com/mike-ward/Markdown-Edit/issues/105

**Comment by jimfoye** [comment]
I believe the first line of GetEndOfLineCaretPosition() should use

`textLine.NewlineLength`

instead of 

`textLine.TrailingWhitespaceLength`

See 

[https://github.com/Microsoft/Windows-classic-samples/blob/cded84bed49cb8ef2095e6470ac83ee3264c4113/Samples/Win7Samples/multimedia/DirectWrite/PadWrite/TextEditor.cpp#L1382](https://github.com/Microsoft/Windows-classic-samples/blob/cded84bed49cb8ef2095e6470ac83ee3264c4113/Samples/Win7Samples/multimedia/DirectWrite/PadWrite/TextEditor.cpp#L1382)

**Comment by jimfoye** [comment]
PR #140
