### ISSUE TITLE
Text Highlighting regex problem with new line

### ISSUE THREAD

**Issue by Kabennsky** [icsharpcode/AvalonEdit#131]
I want to create my own style for LOG-files the highlighted code looks like this:
![image](https://user-images.githubusercontent.com/32191592/32331870-50a0fe8c-bfe4-11e7-931c-dbc6380a28c9.png)
Time in the front blue and the text behind green(information), orange(warning), red(error).
For single line Logs it was no problem but for multiline. So i changed my RuleSet to Spans:
```xml
<SyntaxDefinition name="LOG" extensions=".log" xmlns="http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008">
	
    <Color name="Time" foreground="#38a1d4" />
    <Color name="Info" foreground="#69b26a" />
    <Color name="Warning" foreground="#e1b561" />
    <Color name="Error" foreground="#db5e5e" />
    
	<RuleSet>
        
        <Rule color="Time">\d\d:\d\d:\d\d</Rule>
        <Rule color="Time">\d\d:\d\d:\d\d</Rule>
        
        <Span color="Info" multiline="true">
            <Begin>\[I\]:</Begin>
            <End>[\s\S](?=\n\d\d:\d\d:\d\d)</End>
        </Span>
        <Span color="Warning" multiline="true">
            <Begin>\[W\]:</Begin>
            <End>[\s\S](?=\n\d\d:\d\d:\d\d)</End>
        </Span>
        <Span color="Error" multiline="true">
            <Begin>\[E\]:</Begin>
            <End>[\s\S](?=\n\d\d:\d\d:\d\d)</End>
        </Span>

    </RuleSet>
    
</SyntaxDefinition>
```
But why does the End Span not work for my multiline??
![image](https://user-images.githubusercontent.com/32191592/32332145-02ea2ab4-bfe5-11e7-9221-1ecf14ae6aa6.png)

**Comment by dgrunwald** [comment]
The regular expressions aren't applied to the whole document, but only to individual lines (because the highlighter works incrementally on a line-by-line basis). So there's no way to match `\n`.

Looking at your strange `[\s\S]` class: it should be fine if the `End` regex match has length zero; it's only important that a `Rule` or a whole `Span` has non-zero length so that the highlighter doesn't get stuck in an infinite loop.

So for your case, this span definition might work (untested):
```
        <Span color="Info" multiline="true">
            <Begin>\[I\]:</Begin>
            <End>^(?=\d\d:\d\d:\d\d)</End>
        </Span>
```

**Comment by Kabennsky** [comment]
Ahhh line-by-line gives all this a new face! 
Thank you very much that works :)
