### ISSUE TITLE
Span<T> C# 7.2

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/AvalonEdit#133]
Linking from the forum http://community.sharpdevelop.net/forums/t/26322.aspx

**Comment by jogibear9988** [comment]
But I thought we get realy spanT benefits only with native support from the platform, wich is onlay available at netcore 2 I think?
http://adamsitnik.com/Span/

**Comment by jogibear9988** [comment]
at the moment, nuget is also beta

**Comment by dgrunwald** [comment]
What "performance issues of AvalonEdit due to memory allocation associated with manipulating immutable string type"?

AvalonEdit does not use System.String for the document text; it uses a tree data structure where the leaf nodes hold mutable char arrays. I don't see how `Span<T>` could help with that.
In fact, all text buffer representations that perform well in any text editor do not store the text in a single contiguous array (even a gap text buffer has the gap, hence is not completely contiguous). But `Span<T>` only works with contiguous memory, thus is unusable for editors.

**Comment by goswinr** [comment]
@dgrunwald So is one tree node one line? Or is this unrelated? Are these tree nodes related to visual lines?

**Comment by dgrunwald** [comment]
They are completely unrelated to lines.

Each node holds a char array of a fixed size. If the array gets full, the node is split into two. If two neighboring nodes are near-empty, they are combined again. This results in a text buffer that acts like a mutable string, but with O(lg N) mutations.

There's separate tree-based data structures for the document lines (offset <-> line number mapping) and for the visual lines (y position <-> line number mapping).
