### ISSUE TITLE
Using division in a mathematical expression causes unexpected highlighting

### ISSUE THREAD

**Issue by fdahlberg** [icsharpcode/AvalonEdit#188]
Hi,

I'm using avalon edit with SyntaxHighlighting set to javascript. 
I've noticed that in mathematical expressions containing "/" such as:
"durn2 = manhours/offshore;"
the part after "/" has a different color.

I don't think this should happen. Any ideas why this would be the case?

Kind Regards
Fredrik Dahlberg

**Comment by fdahlberg** [comment]
Was it fixed?

**Comment by siegfriedpammer** [comment]
Yes, I hope so. The fix is not perfect - detecting whether `/` is used as operator or part of a regex literal token would require a full-blown parser, which is not achievable using regexes, but it should work in most cases.

![image](https://user-images.githubusercontent.com/344204/73747026-cc62ad80-4756-11ea-8dda-62cb701b7868.png)

**Comment by fdahlberg** [comment]
Cool! Sounds good! Thanks a lot for doing this.
