### ISSUE TITLE
CompletionWindow NuGet 6.0.1

### ISSUE THREAD

**Issue by Teizakk** [icsharpcode/AvalonEdit#236]
Hello,

I encountered a problem with your nuget package in version 6.0.1. 
When I use that nuget package and try to fill the CompletionWindow with data and then calling the Show Method, the CompletionWindow is empty and the program crashes after another keypress. If I compile your GitHub files manually, the same code suddenly works and the CompletionWindow become filled.
Do you know about anything I could've done wrong?
I'm using VS2019 and I've included the package by the built in NuGet Package Manager

Kind regards

**Comment by siegfriedpammer** [comment]
I just tried to reproduce the problem on my end using the 6.0.1 nuget package, however, I was not able to make it crash. See 
[codecompletionsample.zip](https://github.com/icsharpcode/AvalonEdit/files/6102283/codecompletionsample.zip) for the code I used. If this does not solve your problem, please modify the sample so that it crashes on your machine and send it back to me. Thanks!
