### ISSUE TITLE
Append Text with Color?

### ISSUE THREAD

**Issue by derekantrican** [icsharpcode/AvalonEdit#244]
Hi, new to this control. I'd like to append text to the box with a set color. With the WinForms RichTextBox I would do something like this:

```
        private void AppendTextToLogBoxWithColor(string text, Color color)
        {
            richTextBoxLog.SelectionStart = richTextBoxLog.TextLength;
            richTextBoxLog.SelectionLength = 0;

            richTextBoxLog.SelectionColor = color;
            richTextBoxLog.AppendText(text);
            richTextBoxLog.SelectionColor = richTextBoxLog.ForeColor;
        }
```

I was reading the documentation and saw that I can define custom syntax highlighting rules but is there a simple way to accomplish the same thing with AvalonEdit? Simply appending text with a specific color?

**Comment by blakepell** [comment]
I had a similar issue and I came at it from the same starting point you've got here.  I used AvalonEdit to display colored text from a MUD (which is a text based MMPORG).  The colors come down as ANSI color codes (not a full terminal, but the colors and some formatting).  That text gets written to the terminal (e.g. AvalonEdit).  Think of it like what you're doing here but instead of setting the selection color you're actually putting an ANSI color code into the text.

So, how did I do this?  I used a `DocumentColorizingTransformer`.  That gets called to format a line.  I just write the text with the ANSI into the document and then as AvalonEdit displays it the `DocumentColorizingTransformer` gets called.  In there, I colorize the text based on those ANSI codes (and then hide the ANSI escape sequence in probably a pretty hacky way which was to set the font size to nothing, but it worked for my use case).  Since it's the core of my app I went through that thing and tried to get out every allocation out I could.

Here's a link to that example:

https://github.com/blakepell/AvalonMudClient/blob/master/src/Avalon.Client/Controls/AvalonTerminal/AnsiColorizer.cs

Now, if you have rules like you want to colorize Lua, or HTML, etc. then you can use a `SyntaxDefinition`.  Here's one for Lua:

https://github.com/blakepell/AvalonMudClient/blob/master/src/Avalon.Client/Resources/LuaDarkTheme.xshd

I had that embedded in my program and then told AvalonEdit to use it like this:

```
var asm = Assembly.GetExecutingAssembly();
string resourceName = $"{asm.GetName().Name}.Resources.LuaDarkTheme.xshd";

using (var s = asm.GetManifestResourceStream(resourceName))
{
	using (var reader = new XmlTextReader(s))
	{
		AvalonLuaEditor.SyntaxHighlighting = HighlightingLoader.Load(reader, HighlightingManager.Instance);
	}
}
```

**Comment by derekantrican** [comment]
Thanks for that - I'll have to do some deep digging into your link when I have more time tomorrow. Looks like you intended this "Colorizer" to be on a "per-line" basis? I'm looking for an implementation  that won't necessarily restrict me to line-by-line but can also be applied to, for instance, individual words. Something like:

```
AppendTextToLogBoxWithColor("The color is ", Color.White);
AppendTextToLogBoxWithColor("red", Color.Red);
AppendTextToLogBoxWithColor("!\n", Color.White);
```
Or something similar. I'll have to see if I can modify your example to work

**Comment by blakepell** [comment]
That's correct that the Colorizer runs on a line per line basis but that's just the rendering part (you don't call it per se, you tell AvalonEdit to use it and then it handles calling it when it needs it).  Multiple colors in my case can exist on the same line.  In order to track colors that go across lines I had to track the last color used when text is inserted into the document and then start the next line with that color (I literally put that starting color into the line when it's inserted so when the Colorizer recalls it if it needs to the line is self contained).  Below, I've substituted "{g" for the ANSI dark green, "{G" for the ANSI light green, "{B" he light blue and "{x" is the default color.  The user doesn't see the "{g" stuff, that gets hidden.

```
This is {gDark Green{x and this is {GLight Green
This line starts as green {Bbut ends in blue.{x
```

You can see here how I tracked the last color code (this is an inherited class I use):

https://github.com/blakepell/AvalonMudClient/blob/master/src/Avalon.Client/Controls/AvalonTerminal/AvalonTerminal.cs

Here's a screen shot of the code in action (that colored text is all in an AvalonEdit control).

![image](https://user-images.githubusercontent.com/5958430/94053545-76577e80-fda8-11ea-9dda-c7a31fafd9f3.png)

**Comment by derekantrican** [comment]
Oh nice - Yeah, I've already got some of those things set up like `<!this is an error!>`. So after you do the coloring, do you just remove all the "color keys" afterwards? Or does your coloring process also remove them?

**Comment by dgrunwald** [comment]
AvalonEdit has some classes that can help with implementing something like a rich text editor: `ICSharpCode.AvalonEdit.Highlighting.RichTextModel` is a data structure that can store font style/weight/color; `RichTextColorizer` can apply these during rendering. This way the colors don't need to be part of the `TextDocument`.
Note that you'll manually have to hook these classes up to the editor.

**Comment by blakepell** [comment]
@derekantrican Apologies for the slow reply, I actually don't remove them.  They're needed if the lines have to re-process.  That said, I strip them out if the user copies text out of the terminal/control (I allow them to copy removing the codes or copy with the codes since the game uses them, it's handy for the user to be able to copy and send colored text back to the game).  A long game session can yield a few hundred thousand lines and this has held up well.

I debated going the `RichTextModel` as well but I assumed since I was going to have to parse all the ANSI color codes anyway that I'd just use a Colorize against them directly.  In your case the `RichTextModel` David suggested sounds like a good path.

**Comment by derekantrican** [comment]
Ok, it took quite a bit of digging through the code base, messing around, etc but I found a basic enough example for my situation:

*(Note that I am using a ported version of AvalonEdit: [AvaloniaEdit](https://github.com/AvaloniaUI/AvaloniaEdit)])*

```csharp
RichTextModel richTextModel = new RichTextModel();

public MainWindow()
{
    InitializeComponent();

    TextEditor avaloniaEdit = this.FindControl<TextEditor>("log");
    avaloniaEdit.TextArea.TextView.LineTransformers.Add(new RichTextColorizer(richTextModel));
}

private void AppendTextWithColor(string text, Color color)
{
    TextEditor avaloniaEdit = this.FindControl<TextEditor>("log");
    avaloniaEdit.AppendText(text);
    richTextModel.ApplyHighlighting(avaloniaEdit.Text.Length - text.Length, text.Length, new HighlightingColor() { Foreground = new SimpleHighlightingBrush(color)});
}
```

Thanks for all your help!
