### ISSUE TITLE
Copy text with specified formattings

### ISSUE THREAD

**Issue by dbCF** [icsharpcode/AvalonEdit#260]
Is there a way to copy the formatted text from AvalonEdit into lets say Word and keep the formattings like bold, italic, font and background color?

I don't need it the other way around and I think AvalonEdit's structure doesn't even allow it.

**Comment by siegfriedpammer** [comment]
https://github.com/icsharpcode/AvalonEdit/blob/master/ICSharpCode.AvalonEdit/Highlighting/HtmlClipboard.cs

This should already be used by AvalonEdit out of the box... in fact, using the AvalonEdit sample application I can copy colorized text into Word.

![ae-html-cp](https://user-images.githubusercontent.com/344204/107614354-70284880-6c4a-11eb-9f45-ea4d82cf5d32.gif)

**Comment by dbCF** [comment]
You are not wrong... but it does not work for me.

I have registered an XSHD file as done in https://github.com/icsharpcode/AvalonEdit/blob/106b31efe17a4992e1c02ee5c8650bc86591aeb7/ICSharpCode.AvalonEdit.Sample/Window1.xaml.cs#L45

But my XSHD file is almost empty:
```XML
<?xml version="1.0"?>
<SyntaxDefinition name="Custom Highlighting" xmlns="http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008">
	<RuleSet>
	</RuleSet>
</SyntaxDefinition>
```

Simply because I do not have a fixed set of highlights. The user can specify the highlights during runtime, as suggested in https://github.com/icsharpcode/AvalonEdit/issues/212
```C#
TextEditor.TextArea.TextView.LineTransformers.Add(new CustomDocumentColorizingTransformer());
```

So I am able to copy formatted text IF it is part of the XSHD but the LineTransformations are not considered when copying text.

Any suggestions?

**Comment by siegfriedpammer** [comment]
In order to make this work, you will have to somehow implement the `IHighlighter` interface. Looking at the remarks on that interface, see

https://github.com/icsharpcode/AvalonEdit/blob/9e8ab4b177b537c8e59159e05b5f5f23ff28ceb8/ICSharpCode.AvalonEdit/Highlighting/IHighlighter.cs#L26-L30

you could do this similar to `HighlightingColorizer`, see

https://github.com/icsharpcode/AvalonEdit/blob/106b31efe17a4992e1c02ee5c8650bc86591aeb7/ICSharpCode.AvalonEdit/Highlighting/HighlightingColorizer.cs#L72-L130 

hope this helps!

**Comment by dbCF** [comment]
Thanks for your reply. But I am way too lazy to implement this optional feature myself. For now. Maybe someday. I will let you know if it happens. (:
