### ISSUE TITLE
Rendering selection Top is off by 1 pixel

### ISSUE THREAD

**Issue by nippur72** [icsharpcode/AvalonEdit#38]
The selection box is not correctly aligned in y position with the line and caret, as shown by the following image:

![avalon](https://cloud.githubusercontent.com/assets/2598443/7441777/b134cbbc-f0f6-11e4-913c-6c27533dd216.png)

See how the caret (between `var` and `buffer`) looks shifted up by 1 pixel respect to selection box. The bug is more evident on certain font sizes. 

The above image was produced by having `Options.SelectionBorder.Thickness` = 0 and using a `Consolas` font family and having caret thickness of 2 (in control panel). 

I fixed it by subtracting `0.5` in `BackgroundGeometryBuilder.cs`, but don't know if it's correct:

```C#
double y = visualLine.GetTextLineVisualYPosition(line, VisualYPosition.LineTop)-0.5;
```

**Comment by dgrunwald** [comment]
There's another problem here: the `SelectionLayer` sets geoBuilder.AlignToMiddleOfPixels = true;

By default the selection has a border with thickness 1, and the border lines get centered on the boundary of the geometry. This means the geometry needs to be aligned to the middle of the pixels in order for the border lines to take full pixels.

But when the selection border is disabled, the selection ends up going only to the middle of the pixels, which means you get an anti-aliased border when you requested no border. So we really should use `AlignToWholePixels` instead when the border isn't an odd number of pixels wide.

**Comment by dgrunwald** [comment]
Looks like we're one pixel off intentionally due to commit c992581724. I don't know what the reasoning behind that change was.
Removing that weird `+ 1` would need a lot of testing of the various editor features using the `BackgroundGeometryBuilder`..

**Comment by dgrunwald** [comment]
Looking at the history around that commit, I suspect it's related to the use of AvalonEdit as a single-line TextBox.

**Comment by nippur72** [comment]
Ok, so I switched to having a selection border with thickness = 1, it looks much better and it's also "sharper" as you suggested. 

I see also there is a problem in selection rectangle height too, it's very evident if you have an overstrike-mode caret.

**Comment by dgrunwald** [comment]
I dug into the code a little deeper and found that fonts with odd line heights can cause strange behavior due to `Math.Round` using banker's rounding by default.
I just pushed commit 6f76dd9 which should fix that issue, and makes the `BackgroundGeometryBuilder` consider the border thickness. The selection should now look OK with thickness != 1.

**Comment by dgrunwald** [comment]
The caret height and the selection height should now be equal when `SelectionBorder.Thickness == 0`.
Otherwise, the selection will be bigger due to the border. Whether the additional pixel due to the border is added above or below the border-less selection depends on the exact inputs before rounding :(

In the usual case where the scroll offset and the line heights are all integers, the code should always round up, so that the additional pixel appears below the line.

Interestingly, in the Visual Studio editor, the selection seems to be 2 pixels bigger than the caret: 0.5 pixels to the top, and 1.5 pixels to the bottom (yes, the VS selection is "unsharp").

**Comment by nippur72** [comment]
Great!
